// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smttlncfrydbwkyzzicw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtdHRsbmNmcnlkYndreXp6aWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTk5OTIsImV4cCI6MjA2MDI3NTk5Mn0.rrVvvHnvvGQGovtCQ6hJZjl1L4dDJV16HcuSLhPawTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);